/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ferrari_f40__www.vecarz.com.glb 
Author: Nic Cheung (https://sketchfab.com/heynic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ferrari-f40-wwwvecarzcom-ee082e412b0a4b2090e8492117841e95
Title: Ferrari F40 | www.vecarz.com
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ferrari_f40__www.vecarz.com.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Body_Paint} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Chrome} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Metallic} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_0} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.material_1} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.material_1} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.material_3} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Translucent} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['Rim_-_Black_part']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['Metal_-_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.material_4} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.material} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.material_5} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.material_6} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials['Metal_-_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.material_7} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.material_8} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.material_8} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.material_8} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.material_9} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.material_10} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.material_8} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.material_8} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.material_8} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.material_8} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.material_8} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.material_8} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.Chrome} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.Rubber} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.Metallic} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.material_11} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.Rubber} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.material_12} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.material_12} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.material_8} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials['Metal_-_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_104.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_106.geometry} material={materials['Metal_-_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_108.geometry} material={materials.material_13} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.Rubber} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.Translucent} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.Metallic} position={[0, -0.799, 0.647]} rotation={[-2.209, 0, 0]} />
      <mesh geometry={nodes.Object_116.geometry} material={materials.Headlight_Glass} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_118.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_120.geometry} material={materials.material_14} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_122.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_124.geometry} material={materials.Metallic} position={[0, -0.799, 0.647]} rotation={[-2.209, 0, 0]} />
      <mesh geometry={nodes.Object_126.geometry} material={materials.Translucent} position={[0, -0.799, 0.647]} rotation={[-2.209, 0, 0]} />
      <mesh geometry={nodes.Object_128.geometry} material={materials.material_14} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_130.geometry} material={materials.Translucent} position={[0, -0.799, 0.647]} rotation={[-2.209, 0, 0]} />
      <mesh geometry={nodes.Object_132.geometry} material={materials.material_14} position={[0, -0.799, 0.647]} rotation={[-2.209, 0, 0]} />
      <mesh geometry={nodes.Object_134.geometry} material={materials.Metallic} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_136.geometry} material={materials.Chrome} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_138.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_140.geometry} material={materials.material_10} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_142.geometry} material={materials.Chrome} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_144.geometry} material={materials.material_5} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_146.geometry} material={materials.material_7} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_148.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_150.geometry} material={materials.Chrome} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_152.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_154.geometry} material={materials.material_8} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_156.geometry} material={materials.Rubber} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_158.geometry} material={materials.Metallic} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_160.geometry} material={materials.Rubber} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_162.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_164.geometry} material={materials.Chrome} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_166.geometry} material={materials.material_8} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_168.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_170.geometry} material={materials.material_3} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_172.geometry} material={materials.Chrome} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_174.geometry} material={materials.material_10} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_176.geometry} material={materials.Rubber} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_178.geometry} material={materials.Metallic_0} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_180.geometry} material={materials.material_14} position={[0, -0.799, 0.647]} rotation={[-2.209, 0, 0]} />
      <mesh geometry={nodes.Object_182.geometry} material={materials.material_1} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_184.geometry} material={materials.Mirror} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_186.geometry} material={materials.Mirror} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_188.geometry} material={materials.Mirror} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_190.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_192.geometry} material={materials.material_15} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_194.geometry} material={materials.material_0} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_196.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_198.geometry} material={materials.material_1} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_200.geometry} material={materials.material_16} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_202.geometry} material={materials.material_17} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_204.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_206.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_208.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_210.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_212.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_214.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_216.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_218.geometry} material={materials.material_12} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_220.geometry} material={materials.Rubber} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_222.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_224.geometry} material={materials.Rubber} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_226.geometry} material={materials.Metallic} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_228.geometry} material={materials.material_5} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_230.geometry} material={materials.Rubber} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_232.geometry} material={materials.Rubber} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_234.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_236.geometry} material={materials.Chrome} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_238.geometry} material={materials.Chrome} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_240.geometry} material={materials.Metallic_0} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_242.geometry} material={materials.material_1} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_244.geometry} material={materials.material_18} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_246.geometry} material={materials['Fabric_-_Red']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_248.geometry} material={materials.material_19} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_250.geometry} material={materials.material_8} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_252.geometry} material={materials['Metal_-_Grey']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_254.geometry} material={materials.material_10} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_256.geometry} material={materials.material_20} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_258.geometry} material={materials.material_7} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_260.geometry} material={materials.material_7} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_262.geometry} material={materials.Metallic} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_264.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_266.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_268.geometry} material={materials.Translucent} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_270.geometry} material={materials.Translucent} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_272.geometry} material={materials.Translucent} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_274.geometry} material={materials.Translucent} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_276.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_278.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_280.geometry} material={materials.material_9} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_282.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_284.geometry} material={materials.material} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_286.geometry} material={materials['Rim_-_Black_part']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_288.geometry} material={materials.material_21} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_290.geometry} material={materials.material_9} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_292.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_294.geometry} material={materials.material_21} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_296.geometry} material={materials.material_9} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_298.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_300.geometry} material={materials.material} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_302.geometry} material={materials['Rim_-_Black_part']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_304.geometry} material={materials.material_21} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_306.geometry} material={materials.material_2} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_308.geometry} material={materials.material} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_310.geometry} material={materials['Rim_-_Black_part']} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_312.geometry} material={materials.material_21} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_314.geometry} material={materials.material_22} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_316.geometry} material={materials.material_22} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_318.geometry} material={materials.material_22} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_320.geometry} material={materials.material_22} position={[0, 0.007, -0.049]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/ferrari_f40__www.vecarz.com.glb')
