/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/animated_helicopter.glb 
Author: VertaScan (https://sketchfab.com/VertaScan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-helicopter-cb8067bc7eeb45f1bc08bed0d64a5ae3
Title: Animated Helicopter
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three"; // Import THREE for loop types

export function Helicopter(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "./models/animated_helicopter.glb"
  );
  const { actions } = useAnimations(animations, group);

  // Start animations when the component mounts
  React.useEffect(() => {
    if (actions) {
      // Loop only the rotor animations
      Object.keys(actions).forEach((key) => {
        const action = actions[key];

        // Only loop the rotor animations
        if (key.includes("rotor")) {
          action.play();
          action.setLoop(THREE.LoopRepeat, Infinity); // Infinite loop for rotors
        } else {
          action.stop(); // Stop other animations like doors
        }
      });
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="main_rotor__0"
                position={[0.001, 3.7, -0.006]}
                rotation={[1.492, 0, -Math.PI / 2]}
                scale={1.167}
              >
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials.rubber}
                />
                <mesh
                  name="Object_5"
                  geometry={nodes.Object_5.geometry}
                  material={materials.basematerial}
                />
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials["steel.001"]}
                />
              </group>
              <group
                name="doors004_14"
                position={[0.856, 1.708, 2.613]}
                rotation={[-3.012, -0.002, -3.141]}
                scale={[0.586, 0.914, 0.518]}
              >
                <mesh
                  name="Object_52"
                  geometry={nodes.Object_52.geometry}
                  material={materials.basematerial}
                />
                <mesh
                  name="Object_53"
                  geometry={nodes.Object_53.geometry}
                  material={materials.glass}
                />
                <mesh
                  name="Object_54"
                  geometry={nodes.Object_54.geometry}
                  material={materials.grate}
                />
                <mesh
                  name="Object_55"
                  geometry={nodes.Object_55.geometry}
                  material={materials.trim}
                />
              </group>
              <group
                name="rear_rotor_1"
                position={[-0.001, 2.164, -4.433]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[2.666, 1, 1]}
              >
                <mesh
                  name="Object_8"
                  geometry={nodes.Object_8.geometry}
                  material={materials.rubber}
                />
                <mesh
                  name="Object_9"
                  geometry={nodes.Object_9.geometry}
                  material={materials.bmat}
                />
                <mesh
                  name="Object_10"
                  geometry={nodes.Object_10.geometry}
                  material={materials["steel.001"]}
                />
              </group>
              <group
                name="rear_stabolizer_2"
                position={[0, 2.168, -4.409]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.568, 1.585, 0.568]}
              >
                <mesh
                  name="Object_12"
                  geometry={nodes.Object_12.geometry}
                  material={materials.basematerial}
                />
                <mesh
                  name="Object_13"
                  geometry={nodes.Object_13.geometry}
                  material={materials.lights}
                />
              </group>
              <group
                name="Sphere_3"
                position={[-0.125, 2.163, -4.444]}
                scale={0.072}
              >
                <mesh
                  name="Object_15"
                  geometry={nodes.Object_15.geometry}
                  material={materials.rubber}
                />
              </group>
              <group
                name="Sphere001_4"
                position={[0.126, 2.163, -4.444]}
                scale={0.072}
              >
                <mesh
                  name="Object_17"
                  geometry={nodes.Object_17.geometry}
                  material={materials.rubber}
                />
              </group>
              <group
                name="landing_gear_5"
                position={[-0.003, 0.011, 0.489]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.631, 1.353, 0.873]}
              >
                <mesh
                  name="Object_19"
                  geometry={nodes.Object_19.geometry}
                  material={materials.basematerial}
                />
                <mesh
                  name="Object_20"
                  geometry={nodes.Object_20.geometry}
                  material={materials.rubber}
                />
                <mesh
                  name="Object_21"
                  geometry={nodes.Object_21.geometry}
                  material={materials["steel.001"]}
                />
              </group>
              <group
                name="chasis_6"
                position={[0, 1.5, 0]}
                rotation={[-3.012, 0, -Math.PI]}
                scale={[0.586, 0.914, 0.518]}
              >
                <mesh
                  name="Object_23"
                  geometry={nodes.Object_23.geometry}
                  material={materials.basematerial}
                />
                <mesh
                  name="Object_24"
                  geometry={nodes.Object_24.geometry}
                  material={materials.glass}
                />
                <mesh
                  name="Object_25"
                  geometry={nodes.Object_25.geometry}
                  material={materials.grate}
                />
                <mesh
                  name="Object_26"
                  geometry={nodes.Object_26.geometry}
                  material={materials.lights}
                />
                <mesh
                  name="Object_27"
                  geometry={nodes.Object_27.geometry}
                  material={materials.trim}
                />
              </group>
              <group
                name="seats_Cube002_7"
                position={[0.023, 1.502, 1.655]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={[1.158, 1.158, 1.088]}
              >
                <mesh
                  name="Object_29"
                  geometry={nodes.Object_29.geometry}
                  material={materials.bmat}
                />
                <mesh
                  name="Object_30"
                  geometry={nodes.Object_30.geometry}
                  material={materials["steel.001"]}
                />
              </group>
              <group
                name="seats_Cube001_8"
                position={[0.37, 1.502, 0.873]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={[1.158, 1.158, 1.088]}
              >
                <mesh
                  name="Object_32"
                  geometry={nodes.Object_32.geometry}
                  material={materials.bmat}
                />
                <mesh
                  name="Object_33"
                  geometry={nodes.Object_33.geometry}
                  material={materials["steel.001"]}
                />
              </group>
              <group
                name="seats_Cube003_9"
                position={[-0.328, 1.502, 0.873]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={[1.158, 1.158, 1.088]}
              >
                <mesh
                  name="Object_35"
                  geometry={nodes.Object_35.geometry}
                  material={materials.bmat}
                />
                <mesh
                  name="Object_36"
                  geometry={nodes.Object_36.geometry}
                  material={materials["steel.001"]}
                />
              </group>
              <group
                name="fin_10"
                position={[0, 2.168, -4.409]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.568, 1.585, 0.568]}
              >
                <mesh
                  name="Object_38"
                  geometry={nodes.Object_38.geometry}
                  material={materials.trim}
                />
              </group>
              <group
                name="doors001_11"
                position={[0, 1.5, 0]}
                rotation={[-3.012, 0, -Math.PI]}
                scale={[0.586, 0.914, 0.518]}
              >
                <mesh
                  name="Object_40"
                  geometry={nodes.Object_40.geometry}
                  material={materials.basematerial}
                />
                <mesh
                  name="Object_41"
                  geometry={nodes.Object_41.geometry}
                  material={materials.glass}
                />
                <mesh
                  name="Object_42"
                  geometry={nodes.Object_42.geometry}
                  material={materials.trim}
                />
              </group>
              <group
                name="doors002_12"
                position={[0, 1.5, 0]}
                rotation={[-3.012, 0, -Math.PI]}
                scale={[0.586, 0.914, 0.518]}
              >
                <mesh
                  name="Object_44"
                  geometry={nodes.Object_44.geometry}
                  material={materials.basematerial}
                />
                <mesh
                  name="Object_45"
                  geometry={nodes.Object_45.geometry}
                  material={materials.trim}
                />
              </group>
              <group
                name="doors003_13"
                position={[0.852, 1.686, 2.611]}
                rotation={[-3.012, 0, -Math.PI]}
                scale={[0.586, 0.914, 0.518]}
              >
                <mesh
                  name="Object_47"
                  geometry={nodes.Object_47.geometry}
                  material={materials.basematerial}
                />
                <mesh
                  name="Object_48"
                  geometry={nodes.Object_48.geometry}
                  material={materials.glass}
                />
                <mesh
                  name="Object_49"
                  geometry={nodes.Object_49.geometry}
                  material={materials.grate}
                />
                <mesh
                  name="Object_50"
                  geometry={nodes.Object_50.geometry}
                  material={materials.trim}
                />
              </group>
              <group
                name="doors005_15"
                position={[1.026, 2.142, 1.559]}
                rotation={[-3.012, 0, -Math.PI]}
                scale={[0.586, 0.914, 0.518]}
              >
                <mesh
                  name="Object_57"
                  geometry={nodes.Object_57.geometry}
                  material={materials.basematerial}
                />
                <mesh
                  name="Object_58"
                  geometry={nodes.Object_58.geometry}
                  material={materials.glass}
                />
                <mesh
                  name="Object_59"
                  geometry={nodes.Object_59.geometry}
                  material={materials.trim}
                />
              </group>
              <group
                name="doors006_16"
                position={[0, 1.5, 0]}
                rotation={[-3.012, 0, -Math.PI]}
                scale={[0.586, 0.914, 0.518]}
              >
                <mesh
                  name="Object_61"
                  geometry={nodes.Object_61.geometry}
                  material={materials.basematerial}
                />
                <mesh
                  name="Object_62"
                  geometry={nodes.Object_62.geometry}
                  material={materials.trim}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/animated_helicopter.glb");
