/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/oscilloscope.glb 
Author: University of Wyoming Libraries (https://sketchfab.com/uwlibraries)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/oscilloscope-368c3efcb42e4f03bd41e59a7dab3718
Title: Oscilloscope
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import gsap from "gsap";
import { useFrame } from "@react-three/fiber";

export function Oscilloscope(props) {
  const { nodes, materials } = useGLTF("./models/oscilloscope.glb");

  const ref = useRef();

  useFrame((state, delta) => {
    // Increment the rotation on the y-axis for continuous rotation
    if (ref.current) {
      ref.current.rotation.y += delta; // Adjust speed by scaling delta
    }
  });

  useLayoutEffect(() => {
    // Optional: Initialize any starting rotation or animations
    gsap.to(ref.current.rotation, {
      y: 2 * Math.PI,
      duration: 10,
      repeat: -1, // Infinite repeat
      ease: "linear", // Smooth constant speed
    });
  }, []);

  return (
    <group {...props} dispose={null} ref={ref}>
      <group
        position={[-0.284, 0.368, 0.086]}
        rotation={[-0.888, 1.549, 0.887]}
      >
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            geometry={nodes.Model_material3_0.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_1.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_2.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_3.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_4.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_5.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_6.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_7.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_8.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_9.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_10.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_11.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_12.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_13.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_14.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_15.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_16.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material3_0_17.geometry}
            material={materials.material3}
          />
          <mesh
            geometry={nodes.Model_material2_0.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_1.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_2.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_3.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_4.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_5.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_6.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_7.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_8.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_9.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_10.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_11.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_12.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_13.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_14.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_15.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_16.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_17.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material2_0_18.geometry}
            material={materials.material2}
          />
          <mesh
            geometry={nodes.Model_material1_0.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_1.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_2.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_3.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_4.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_5.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_6.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_7.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_8.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_9.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_10.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_11.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_12.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_13.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_14.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_15.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_16.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_17.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_18.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material0_0.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_1.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_2.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_3.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_4.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_5.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_6.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_7.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_8.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_9.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_10.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_11.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_12.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_13.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_14.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_15.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_16.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_17.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_18.geometry}
            material={materials.material0}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/oscilloscope.glb");
